---
title: "Soil Data Exploration"
author: "German Silva"
date: "3/4/2022"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning = FALSE)

# visualization
library(mapview)
library(calecopal)

# significance tests and data exploration
library(tidyverse)
library(here)
library(kableExtra)
library(ggbeeswarm)
library(broom)
library(randomForest)
library(randomForestExplainer)
library(caret)
library(ggfortify)
library(tsibble)

# spatial analysis
library(sf)
library(tmap)
library(gstat)
library(stars)
library(terra)
library(SpatialKDE)

set.seed(1234)
```

# Opening and exploring data

## Open and explore precip data:

```{r, dpi=600}
precip <- read_csv(here("data", "precip_data", "copr_all.txt")) %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date(timestamp)) %>% 
  select(date, rain_mm_tot) %>% 
  mutate(date = lubridate::ymd(date),
         month = lubridate::month(date),
         year = lubridate::year(date),
         day = lubridate::yday(date))

precip_d_2022 <- precip %>%
  drop_na() %>% 
  filter(year == 2022,
         month %in% c(2,3,4,5,6)) %>% 
  group_by(date) %>% 
  summarize(daily_precip = sum(rain_mm_tot))

precip_monthly <- precip %>% 
  drop_na() %>% 
  group_by(month, year) %>% 
  summarize(monthly_precip = sum(rain_mm_tot)) %>% 
  ungroup()

precip_2022 <- precip_monthly %>% 
  filter(year == 2022) %>% 
  mutate(precip_2022 = monthly_precip) %>% 
  select(month, precip_2022)

precip_avg <- precip_monthly %>% 
  group_by(month) %>% 
  summarize(month_avg = mean(monthly_precip)) %>% 
  ungroup()

precip_data <- merge(precip_avg, precip_2022) %>% 
  mutate(month = factor(month.abb[month], levels = month.abb))


colors <- c("Monthly Avg." = "#8f96a6", '2022 Monthly' = "#356575")

ggplot(data = precip_data)+
  geom_col(aes(x = month, y = month_avg, fill = "Monthly Avg."), alpha = 0.75)+
  geom_col(aes(x = month, y = precip_2022, fill = "2022 Monthly"), alpha = 0.85)+
  geom_rect(aes(xmin = "Feb", xmax = "May", ymin = 0, ymax = Inf), alpha = 0.0070)+
  labs(x = "Month",#labels
       y = "Precipitation (mm)",
       fill = "Legend",
       title = "Monthly Rainfall at Devereux Slough")+
  scale_fill_manual(values = colors)+
  theme(plot.title = element_text(color = "#5b4f41", size = 20, hjust = 0.5),# plot theming
        plot.background = element_rect("white"),
        panel.background = element_rect("#faf7f2"),
        panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
        axis.text = element_text(color = "#5b4f41", size = 14),
        axis.title = element_text(color = "#5b4f41", size = 16),
        strip.background = element_rect("#f8f8f8"),
        strip.text = element_text(color = "#5b4f41"),
        axis.line = element_line(color = "#5b4f41"),
        legend.text = element_text(color = "#5b4f41"),
        legend.title = element_text(color = "#5b4f41"))
```


## Open soil and elevation data:

```{r}
#opening csv
soils <- read_csv(here("data", "shift_soil_data.csv")) %>% # read in soil csv
  mutate(date = lubridate::mdy(date), # change to date class
         week = lubridate::week(date)) %>% # create a week column
  select(soil_id:transect, meter_location, electro_cond_mS_per_cm, season, latitude, longitude, landcover)%>% #select certain column to work with
  mutate(paired_flight = lubridate::ymd(paired_flight)) %>% 
  drop_na() %>%  #drop any NA rows
  st_as_sf(coords = c("longitude", "latitude")) %>% 
  st_set_crs(value = 4326) %>% 
  st_transform(crs = 32611)


# Open spatial Data
soils_sf <- read_sf(here("data", "soil_w_elevation.shp")) %>% # read in sf file
  mutate(date = lubridate::ymd(date), #change date to date class
         week = lubridate::week(date)) %>% #create week
  select(electro_co, date, transect, meter_loca) %>% # select certain columns
  filter(date != "2022-09-12") %>% 
  mutate(electro_co = as.numeric(electro_co)) %>% #change to numeric class
  drop_na() #drop NAs

bbox <- read_sf(here("data", "bbox.shp")) #read in bounding box file

boundary <- read_sf(here("data", "boundary.shp")) %>% 
  st_transform(crs = 32611)

dem <- read_stars(here("data", "dem.tif")) %>% # read in dem 
  st_crop(y = st_bbox(bbox)) %>%  #crop to bounding box
  st_warp(cellsize = 4.8, crs = 32611)

mllw <- dem + 0.042

mllw_all <- c(mllw, mllw, mllw, mllw, mllw, mllw, mllw, mllw, mllw, mllw, mllw, mllw, mllw, along = 3) %>%
  st_set_dimensions(3, values = lubridate::ymd(c("2022_02_24", "2022_02_28", "2022_03_08", "2022_03_16", "2022_03_22", "2022_04_05", "2022_04_12", "2022_04_20", "2022_04_29", "2022_05_03", "2022_05_11", "2022_05_17", "2022_05_29")), names = "date")

mllw_extract <- mllw %>% # call dem
  st_extract(soils$geometry) # extract elevation to point layer

```


## Join soil and elevation data:
```{r}
soils <- cbind(soils, mllw_extract$dem.tif) %>% #bind extracted values to the soil data
  rename("elevation" = "mllw_extract.dem.tif") %>% 
  st_transform(crs = 32611)
```

## Descriptive statistics:
```{r}
#make descriptive stat table
soils %>% # to soils
  group_by(transect) %>%# group by transect 
  st_drop_geometry() %>% 
  summarize(Min = min(electro_cond_mS_per_cm),#calculate mins
            Max = max(electro_cond_mS_per_cm),#calculate max
            Mean = mean(electro_cond_mS_per_cm),#calculate mean
            Median = median(electro_cond_mS_per_cm),
            St_Dev = sd(electro_cond_mS_per_cm),#obtain standard dev
            Variance = var(electro_cond_mS_per_cm)) %>% # calculate variance
  kableExtra::kable() %>% # create a table format
  kableExtra::kable_classic(lightable_options = "striped")#theme the table

# make descriptive stat dataframe
soil_stats <- soils %>% #call soils
  group_by(transect) %>% #group by transects
  summarize(mean = mean(electro_cond_mS_per_cm),# create dataframe with these stats
            max = max(electro_cond_mS_per_cm),
            min = min(electro_cond_mS_per_cm),
            range = max - min)

summary(aov(electro_cond_mS_per_cm ~ transect*date*elevation, data = soils))

TukeyHSD(aov(electro_cond_mS_per_cm ~ transect, data = soils))
```

## Plot salinity v elevation
```{r, dpi=600}
ggplot(soils, aes(x = elevation, y = electro_cond_mS_per_cm, color = transect)) +#ggplot of soils/dem data
  geom_point()+#geometry of the plot
  scale_color_manual(values = calecopal::cal_palette(name = "superbloom3", n =6, type = "discrete"))+# colors to use
  labs(x = "Elevation (m)",#labels
       y = "Electrical conductivity (mS/cm)")+
  #theme(legend.position = "none")+#no legend theme
  guides(color = guide_legend(title = "Transect ID"))+#changing legend title
  ggtitle("Soil Electrical Conductivity Across Elevations")+# title of plot
  theme(plot.title = element_text(color = "#5b4f41", size = 20, hjust = -0.5),# plot theming
        plot.background = element_rect("white"),
        panel.background = element_rect("#faf7f2"),
        panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
        axis.text = element_text(color = "#5b4f41", size = 14),
        axis.title = element_text(color = "#5b4f41", size = 16),
        strip.background = element_rect("#f8f8f8"),
        strip.text = element_text(color = "#5b4f41"),
        axis.line = element_line(color = "#5b4f41"),
        legend.text = element_text(color = "#5b4f41"),
        legend.title = element_text(color = "#5b4f41"))
```

## Salinity vs. elevation, facet wrapped
```{r}
strip_labels <- c("COPR_1_EW" = "COPR 1 EW",#create better formated labels for facet wrap strips
                  "COPR_2_EW" = "COPR 2 EW",
                  "COPR_2_NS" = "COPR 2 NS",
                  "NCOS_1_NS" = "NCOS 1 NS",
                  "NCOS_2_EW" = "NCOS 2 EW",
                  "NCOS_2_NS" = "NCOS 2 NS")

ggplot(soils, aes(x = elevation, y = electro_cond_mS_per_cm, color = transect)) +#start ggplot
  geom_jitter()+# point geometry
  scale_color_manual(values = calecopal::cal_palette(name = "superbloom3", n =6, type = "discrete"))+#colors
  facet_wrap(~transect, labeller = as_labeller(strip_labels))+#subplots based on transect
  theme(legend.position = "none")+# legend theme
  labs(x = "Elevation (m)",#labels
       y = "Electrical conductivity (mS/cm)")+
  guides(color = guide_legend(title = "Transect ID"))+#legend title
  ggtitle("Soil Electrical Conductivity Across Elevations")+#plot title
  theme(plot.title = element_text(color = "#5b4f41", size = 16, hjust = 0.5),#plot theme
        plot.background = element_rect("white"),
        panel.background = element_rect("#faf7f2"),
        panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
        axis.text = element_text(color = "#5b4f41"),
        axis.title = element_text(color = "#5b4f41"),
        strip.background = element_rect("#f8f8f8"),
        strip.text = element_text(color = "#5b4f41"),
        axis.line = element_line(color = "#5b4f41"),
        legend.text = element_text(color = "#5b4f41"),
        legend.title = element_text(color = "#5b4f41"))
```

```{r, dpi=600}
soil_sum <- soils %>% 
  group_by(transect, date) %>% 
  summarise(avg_ec = mean(electro_cond_mS_per_cm),
            max_ec = max(electro_cond_mS_per_cm),
            min_ec = min(electro_cond_mS_per_cm),
            med_ec = median(electro_cond_mS_per_cm))

precip_shift <- precip_d_2022 %>% 
  mutate(month = month(date),
         week = week(date)) %>% 
  filter(week %in% c(8:22))

ggplot()+
  geom_line(data = precip_shift, aes(x = date, y = daily_precip * 0.394), color = "#356575")+
  geom_point(data = soils, aes(x = date, y = electro_cond_mS_per_cm, color = transect))+# point geometry
  geom_smooth(data = soils, aes(x = date, y = electro_cond_mS_per_cm, color = transect))+
  scale_color_manual(values = calecopal::cal_palette(name = "superbloom3", n =6, type = "discrete"))+#colors
  scale_y_continuous(name = "Electrical Conductivity mS/cm",
                     sec.axis = sec_axis(trans = ~.*2.54, name = "Precipitation (mm)"))+
  facet_wrap(~transect, labeller = as_labeller(strip_labels))+#subplots based on transect
  theme(legend.position = "none")+# legend theme
  labs(x = "Date",#labels
       y = "Electrical conductivity (mS/cm)")+
  guides(color = guide_legend(title = "Transect ID"))+#legend title
  ggtitle("Soil Electrical Conductivity by Date w/ Daily Precip.")+#plot title
  theme(plot.title = element_text(color = "#5b4f41", size = 16, hjust = 0.5),#plot theme
        plot.background = element_rect("white"),
        panel.background = element_rect("#faf7f2"),
        panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
        axis.text = element_text(color = "#5b4f41"),
        axis.title = element_text(color = "#5b4f41"),
        axis.line.y.right = element_line(color =  "#356575"), 
        axis.ticks.y.right = element_line(color = "#356575"),
        axis.text.y.right = element_text(color = "#356575"), 
        axis.title.y.right = element_text(color = "#356575"),
        strip.background = element_rect("#f8f8f8"),
        strip.text = element_text(color = "#5b4f41"),
        axis.line = element_line(color = "#5b4f41"),
        legend.text = element_text(color = "#5b4f41"),
        legend.title = element_text(color = "#5b4f41"))

ggsave(filename = "ec_precip_ts.jpg", dpi = 600)

# ggplot()+
#   geom_line(data = precip_shift, aes(x = date, y = daily_precip * 0.394), color = "#356575")+
#   geom_point(data = soil_sum, aes(x = date, y = avg_ec, color = transect))+# point geometry
#   geom_smooth(data = soil_sum, aes(x = date, y = avg_ec, color = transect))+
#    scale_y_continuous(name = "Electrical Conductivity mS/cm",
#                      sec.axis = sec_axis(trans = ~.*2.54, name = "Percipitation (mm)"))+
#   scale_color_manual(values = calecopal::cal_palette(name = "superbloom3", n =6, type = "discrete"))+#colors
#   facet_wrap(~transect, labeller = as_labeller(strip_labels))+#subplots based on transect
#   theme(legend.position = "none")+# legend theme
#   labs(x = "Date",#labels
#        y = "Electrical conductivity (mS/cm)")+
#   guides(color = guide_legend(title = "Transect ID"))+#legend title
#   ggtitle("Average Soil Electrical Conductivity by Date w/ Daily Precip.")+#plot title
#   theme(plot.title = element_text(color = "#5b4f41", size = 16, hjust = 0.5),#plot theme
#         plot.background = element_rect("white"),
#         panel.background = element_rect("#faf7f2"),
#         panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
#         axis.text = element_text(color = "#5b4f41"),
#         axis.title = element_text(color = "#5b4f41"),
#         axis.line.y.right = element_line(color =  "#356575"), 
#         axis.ticks.y.right = element_line(color = "#356575"),
#         axis.text.y.right = element_text(color = "#356575"), 
#         axis.title.y.right = element_text(color = "#356575"),
#         strip.background = element_rect("#f8f8f8"),
#         strip.text = element_text(color = "#5b4f41"),
#         axis.line = element_line(color = "#5b4f41"),
#         legend.text = element_text(color = "#5b4f41"),
#         legend.title = element_text(color = "#5b4f41"))

# ggplot()+
#   geom_point(data = soil_sum, aes(x = paired_flight, y = max_ec, color = transect))+# point geometry
#   geom_smooth(data = soil_sum, aes(x = paired_flight, y = max_ec, color = transect))+
#   scale_color_manual(values = calecopal::cal_palette(name = "superbloom3", n =6, type = "discrete"))+#colors
#   geom_vline(xintercept = lubridate::ymd("2022_03_20"), alpha = 0.20)+
#   geom_vline(xintercept = lubridate::ymd("2022_03_28"), alpha = 0.45)+
#    geom_vline(xintercept = lubridate::ymd("2022_03_29"), alpha = 0.0)+
#    geom_vline(xintercept = lubridate::ymd("2022_04_22"), alpha = 0.45)+
#   facet_wrap(~transect, labeller = as_labeller(strip_labels))+#subplots based on transect
#   theme(legend.position = "none")+# legend theme
#   labs(x = "Date",#labels
#        y = "Electrical conductivity (mS/cm)")+
#   guides(color = guide_legend(title = "Transect ID"))+#legend title
#   ggtitle("Max. Soil Electrical Conductivity by Transect and Date")+#plot title
#   theme(plot.title = element_text(color = "#5b4f41", size = 16, hjust = 0.5),#plot theme
#         plot.background = element_rect("white"),
#         panel.background = element_rect("#faf7f2"),
#         panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
#         axis.text = element_text(color = "#5b4f41"),
#         axis.title = element_text(color = "#5b4f41"),
#         strip.background = element_rect("#f8f8f8"),
#         strip.text = element_text(color = "#5b4f41"),
#         axis.line = element_line(color = "#5b4f41"),
#         legend.text = element_text(color = "#5b4f41"),
#         legend.title = element_text(color = "#5b4f41"))
```


