---
title: "spectra plotting"
author: "Germán Silva"
date: "2024-06-13"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning = FALSE)

# visualization
library(calecopal)

# significance tests and data exploration
library(tidyverse)
library(here)
library(broom)
library(ggfortify)


set.seed(1234)
```


```{r}

copr_spec <- read_csv(here("data", "example_spectra", "copr_2_ns_02.csv")) %>% 
  pivot_longer(cols = c(High:Low), names_to = "location", values_to = "reflectance") %>% 
  mutate(Wavelength = case_when(
    Band %in% c(3:195, 210:285, 313:325, 327:420) ~ Wavelength,
    Band %in% c(1:2, 196:209, 286:312, 326, 421:25) ~ NA)) %>% 
  mutate(location = factor(location, levels = c("High", "Mid 1", "Mid 2", "Low")))

ggplot(copr_spec)+
  geom_rect(aes(xmin = 540, xmax = 560, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 690, xmax = 710, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 760, xmax = 800, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_path(aes(x = Wavelength, y = reflectance, color = location))+
  scale_color_manual(values = c("#3A5D3D","#E69512", "#D3105C", "#6D4847"))+# colors to use
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.45))+
  labs(x = "Wavelength (nm)",#labels
       y = "Reflectance",
       color = "Relative 
Elevation")+
  ggtitle("COPR 2 NS Spectra Feb. 2022")+# title of plot
   theme(plot.title = element_text(color = "#5b4f41", size = 20, hjust = 0.5),# plot theming
        plot.background = element_rect("white"),
        panel.background = element_rect("#faf7f2"),
        panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
        axis.text = element_text(color = "#5b4f41", size = 14),
        axis.title = element_text(color = "#5b4f41", size = 16),
        strip.background = element_rect("#f8f8f8"),
        strip.text = element_text(color = "#5b4f41"),
        axis.line = element_line(color = "#5b4f41"),
        legend.text = element_text(color = "#5b4f41", size = 12),
        legend.title = element_text(color = "#5b4f41", size = 14))


```

```{r}

copr_spec <- read_csv(here("data", "example_spectra", "copr_2_ns_05.csv")) %>% 
  pivot_longer(cols = c(High:Low), names_to = "location", values_to = "reflectance") %>% 
   mutate(Wavelength = case_when(
    Band %in% c(3:195, 210:285, 313:325, 327:420) ~ Wavelength,
    Band %in% c(1:2, 196:209, 286:312, 326, 421:25) ~ NA)) %>%  
  mutate(location = factor(location, levels = c("High", "Mid 1", "Mid 2", "Low")))

ggplot(copr_spec)+
  geom_rect(aes(xmin = 540, xmax = 560, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 690, xmax = 710, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 760, xmax = 800, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_path(aes(x = Wavelength, y = reflectance, color = location))+
  scale_color_manual(values = c("#3A5D3D","#E69512", "#D3105C", "#6D4847"))+# colors to use
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.45))+
  labs(x = "Wavelength (nm)",#labels
       y = "Reflectance",
       color = "Relative 
Elevation")+
  ggtitle("COPR 2 NS Spectra May 2022")+# title of plot
   theme(plot.title = element_text(color = "#5b4f41", size = 20, hjust = 0.5),# plot theming
        plot.background = element_rect("white"),
        panel.background = element_rect("#faf7f2"),
        panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
        axis.text = element_text(color = "#5b4f41", size = 14),
        axis.title = element_text(color = "#5b4f41", size = 16),
        strip.background = element_rect("#f8f8f8"),
        strip.text = element_text(color = "#5b4f41"),
        axis.line = element_line(color = "#5b4f41"),
        legend.text = element_text(color = "#5b4f41", size = 12),
        legend.title = element_text(color = "#5b4f41", size = 14))


```



```{r}

ncos_1_spec <- read_csv(here("data", "example_spectra", "ncos_1_02.csv")) %>% 
  pivot_longer(cols = c(High:Low), names_to = "location", values_to = "reflectance") %>% 
   mutate(Wavelength = case_when(
    Band %in% c(3:195, 210:285, 313:325, 327:420) ~ Wavelength,
    Band %in% c(1:2, 196:209, 286:312, 326, 421:25) ~ NA)) %>% 
  mutate(location = factor(location, levels = c("High", "Mid 1", "Mid 2", "Low")))

ggplot(ncos_1_spec)+
  geom_rect(aes(xmin = 540, xmax = 560, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 690, xmax = 710, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 760, xmax = 800, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_path(aes(x = Wavelength, y = reflectance, color = location))+
  scale_color_manual(values = c("#3A5D3D","#E69512", "#D3105C", "#6D4847"))+# colors to use
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.45))+
  labs(x = "Wavelength (nm)",#labels
       y = "Reflectance",
       color = "Relative 
Elevation")+
  ggtitle("NCOS 1 NS Spectra Feb. 2022")+# title of plot
  theme(plot.title = element_text(color = "#5b4f41", size = 20, hjust = 0.5),# plot theming
        plot.background = element_rect("white"),
        panel.background = element_rect("#faf7f2"),
        panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
        axis.text = element_text(color = "#5b4f41", size = 14),
        axis.title = element_text(color = "#5b4f41", size = 16),
        strip.background = element_rect("#f8f8f8"),
        strip.text = element_text(color = "#5b4f41"),
        axis.line = element_line(color = "#5b4f41"),
        legend.text = element_text(color = "#5b4f41", size = 12),
        legend.title = element_text(color = "#5b4f41", size = 14))

```


```{r}

ncos_1_spec <- read_csv(here("data", "example_spectra", "ncos_1_05.csv")) %>% 
  pivot_longer(cols = c(High:Low), names_to = "location", values_to = "reflectance") %>% 
   mutate(Wavelength = case_when(
    Band %in% c(3:195, 210:285, 313:325, 327:420) ~ Wavelength,
    Band %in% c(1:2, 196:209, 286:312, 326, 421:25) ~ NA)) %>% 
  mutate(location = factor(location, levels = c("High", "Mid 1", "Mid 2", "Low")))

ggplot(ncos_1_spec)+
  geom_rect(aes(xmin = 540, xmax = 560, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 690, xmax = 710, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 760, xmax = 800, ymin = 0, ymax = Inf), alpha = 0.0040)+
   geom_path(aes(x = Wavelength, y = reflectance, color = location))+
  scale_color_manual(values = c("#3A5D3D","#E69512", "#D3105C", "#6D4847"))+# colors to use
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.45))+
  labs(x = "Wavelength (nm)",#labels
       y = "Reflectance",
       color = "Relative 
Elevation")+
  ggtitle("NCOS 1 NS Spectra May 2022")+# title of plot
  theme(plot.title = element_text(color = "#5b4f41", size = 20, hjust = 0.5),# plot theming
        plot.background = element_rect("white"),
        panel.background = element_rect("#faf7f2"),
        panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
        axis.text = element_text(color = "#5b4f41", size = 14),
        axis.title = element_text(color = "#5b4f41", size = 16),
        strip.background = element_rect("#f8f8f8"),
        strip.text = element_text(color = "#5b4f41"),
        axis.line = element_line(color = "#5b4f41"),
        legend.text = element_text(color = "#5b4f41", size = 12),
        legend.title = element_text(color = "#5b4f41", size = 14))

```





```{r}

ncos_2_spec <- read_csv(here("data", "example_spectra", "ncos_2_ew_02.csv")) %>% 
  pivot_longer(cols = c(High:Low), names_to = "location", values_to = "reflectance") %>% 
   mutate(Wavelength = case_when(
    Band %in% c(3:195, 210:285, 313:325, 327:420) ~ Wavelength,
    Band %in% c(1:2, 196:209, 286:312, 326, 421:25) ~ NA)) %>% 
  mutate(location = factor(location, levels = c("High", "Mid 1", "Mid 2", "Low")))

ggplot(ncos_2_spec)+
  geom_rect(aes(xmin = 540, xmax = 560, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 690, xmax = 710, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 760, xmax = 800, ymin = 0, ymax = Inf), alpha = 0.0040)+
   geom_path(aes(x = Wavelength, y = reflectance, color = location))+
  scale_color_manual(values = c("#3A5D3D","#E69512", "#D3105C", "#6D4847"))+# colors to use
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.45))+
  labs(x = "Wavelength (nm)",#labels
       y = "Reflectance",
       color = "Relative 
Elevation")+
  ggtitle("NCOS 2 EW Spectra Feb. 2022")+# title of plot
   theme(plot.title = element_text(color = "#5b4f41", size = 20, hjust = 0.5),# plot theming
        plot.background = element_rect("white"),
        panel.background = element_rect("#faf7f2"),
        panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
        axis.text = element_text(color = "#5b4f41", size = 14),
        axis.title = element_text(color = "#5b4f41", size = 16),
        strip.background = element_rect("#f8f8f8"),
        strip.text = element_text(color = "#5b4f41"),
        axis.line = element_line(color = "#5b4f41"),
        legend.text = element_text(color = "#5b4f41", size = 12),
        legend.title = element_text(color = "#5b4f41", size = 14))

```


```{r}

ncos_2_spec <- read_csv(here("data", "example_spectra", "ncos_2_ew_05.csv")) %>% 
  pivot_longer(cols = c(High:Low), names_to = "location", values_to = "reflectance") %>% 
   mutate(Wavelength = case_when(
    Band %in% c(3:195, 210:285, 313:325, 327:420) ~ Wavelength,
    Band %in% c(1:2, 196:209, 286:312, 326, 421:25) ~ NA)) %>% 
  mutate(location = factor(location, levels = c("High", "Mid 1", "Mid 2", "Low")))

ggplot(ncos_2_spec)+
  geom_rect(aes(xmin = 540, xmax = 560, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 690, xmax = 710, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_rect(aes(xmin = 760, xmax = 800, ymin = 0, ymax = Inf), alpha = 0.0040)+
  geom_path(aes(x = Wavelength, y = reflectance, color = location))+
  scale_color_manual(values = c("#3A5D3D","#E69512", "#D3105C", "#6D4847"))+# colors to use
  scale_y_continuous(expand = c(0, 0), limits = c(0, 0.45))+
  labs(x = "Wavelength (nm)",#labels
       y = "Reflectance",
       color = "Relative 
Elevation")+
  ggtitle("NCOS 2 EW Spectra May 2022")+# title of plot
   theme(plot.title = element_text(color = "#5b4f41", size = 20, hjust = 0.5),# plot theming
        plot.background = element_rect("white"),
        panel.background = element_rect("#faf7f2"),
        panel.grid = element_line(linetype= "longdash", color = "#f0ece1"),
        axis.text = element_text(color = "#5b4f41", size = 14),
        axis.title = element_text(color = "#5b4f41", size = 16),
        strip.background = element_rect("#f8f8f8"),
        strip.text = element_text(color = "#5b4f41"),
        axis.line = element_line(color = "#5b4f41"),
        legend.text = element_text(color = "#5b4f41", size = 12),
        legend.title = element_text(color = "#5b4f41", size = 14))

```



# Spectral ANOVA

```{r}
spectra <- read.csv(here("data", "example_spectra", "example_spectra.csv")) %>% 
  filter(band %in% c(3:195, 210:285, 313:325, 327:420))


summary(aov(reflectance ~ transect*date, data = spectra))

TukeyHSD(aov(reflectance ~ transect*date, data = spectra))
```

```{r}
spectra_wider <- spectra %>% 
  pivot_wider(names_from = elevation, values_from = reflectance)

spectral_angle <- spectra_wider %>% 
  mutate(A_B = (High * `Mid 1`),
         A_C = (High * `Mid 2`),
         A_D = (High * Low),
         A_sq = (High * High),
         B_sq = (`Mid 1` * `Mid 1`),
         C_sq = (`Mid 2` * `Mid 2`),
         D_sq = (Low * Low)) %>% 
  group_by(transect, date) %>% 
  summarize(ab = sum(A_B),
             ac = sum(A_C),
             ad = sum(A_D),
            a_sq = sum(A_sq),
            b_sq = sum(B_sq),
            c_sq = sum(C_sq),
            d_sq = sum(D_sq)) %>% 
  ungroup() %>% 
  mutate(angle_ab = acos((ab)/(sqrt(a_sq)* sqrt(b_sq)))* (180/pi),
         angle_ac = acos((ac)/(sqrt(a_sq)* sqrt(c_sq)))* (180/pi),
         angle_ad = acos((ad)/(sqrt(a_sq)* sqrt(d_sq)))* (180/pi))
```

